### ISSUE TITLE
PSW - Ajustes no trabalho anterior (conforme feedback)

### ISSUE THREAD

**Issue by Lucaslsps** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#11]
Data Máxima de entrega: 30/11/2020 Horário: 23:59

**Comment by llcruz1** [comment]
Nas tabelas das seguintes páginas:

- [Partidas](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Partidas)

- [Nova Partida](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Nova-Partida)

- [Ranking](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Ranking)

- [Novo Jogador](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-Jogador)

- [Novo Time](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-Time)

- [Novo ADM](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-ADM)

- [Perfil](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Perfil)

Tempo estimado na tarefa: 1hr
