### ISSUE TITLE
Testes - Começar a estudar Jest (opcional)

### ISSUE THREAD

**Issue by Lucaslsps** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#16]
É a bibliteca que utilizaremos para os testes unitários (próximo trabalho).

09/12 - 3 horas
10/12 - 3 horas

**Comment by ClaudioBotelhOSB** [comment]
Até o fim do sprint em questão a equipe de Teste não conseguiu terminar os estudos de Jest.
