### ISSUE TITLE
PSW - Estilização do front-end

### ISSUE THREAD

**Issue by Lucaslsps** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#18]
Estilização do front-end para ser responsivo/mobile-like.

**Comment by llcruz1** [comment]
No arquivo [App.js](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/blob/main/src/front-end/src/App.js) e pasta [Layout](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/tree/main/src/front-end/src/components/layout).

Tempo estimado na tarefa: 2hrs
