### ISSUE TITLE
PSW - Correções do projeto

### ISSUE THREAD

**Issue by misterx901** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#2]
Tarefa:  Fazer as alterações solicitadas na interação anterior.

Artefato:
[Matriz Crud](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Matriz-CRUD)

Horas Gastas: 1 hora.

Data Máxima de entrega: 12/11/2020 Horário: 12:00

**Comment by llcruz1** [comment]
@llcruz1 
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Matriz-CRUD

Tempo estimado na tarefa: 1hr
