### ISSUE TITLE
PSW - Definir Domínio Dos Campos

### ISSUE THREAD

**Issue by misterx901** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#3]
Tarefa: Definir os domínio dos campos (faixa de valores válidos e inválidos)

Artefato:
- [Partidas](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Partidas)

- [Nova Partida](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Nova-Partida)

- [Ranking](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Ranking)

- [Novo Jogador](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-Jogador)

- [Novo Time](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-Time)

- [Novo ADM](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-ADM)

- [Perfil](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Perfil)

Horas  Gastas: 1 hora.

Data Máxima de entrega: 12/11/2020 Horário: 12:00

**Comment by llcruz1** [comment]
@llcruz1 
Nas tabelas das seguintes páginas:

- [Partidas](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Partidas)

- [Nova Partida](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Nova-Partida)

- [Ranking](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Ranking)

- [Novo Jogador](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-Jogador)

- [Novo Time](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-Time)

- [Novo ADM](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-ADM)

- [Perfil](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Perfil)

Tempo estimado na tarefa: 1hr
