### ISSUE TITLE
PSW -  Fazer Matriz Perfi x Funcionalidade

### ISSUE THREAD

**Issue by misterx901** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#4]
Tarefa: Definir os perfis de acesso e variações nos protótipos (para cada perfil de acesso analisar se há variação nos protótipos, e, se houver, produzir a variação). Para facilitar esta análise façam a Matriz Perfi x Funcionalidade, onde, uma dimensão são os perfis de acesso e a outra as funcionalidade, marque um X na célula onde o perfil tem acesso a funcionalidade. Para cada funcionalidade onde exista mais de um perfil com acesso verifique se existem variações na exibição da tela.

Artefato:

[Matriz Perfil x Funcionalidade](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Matriz-Perfil-x-Funcionalidade)

Defini os perfis de acesso ADM e Visitante e adicionei as seguintes telas no protótipo:

- [Login](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Login)
- [Partidas Visitante](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Partidas#perfil-de-acesso-visitante)
- [Ranking Visitante](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Ranking#perfil-de-acesso-visitante)
- [Perfil](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Perfil)

Adicionei novas funcionalidades relacionadas ao cadastro de adms nas páginas:

- [Cadastros](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Cadastros)
- [ADMs](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/ADMs)
- [Novo ADM](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-ADM)

Horas Gastas: 3 horas.

Data Máxima de entrega: 12/11/2020 Horário: 12:00

**Comment by llcruz1** [comment]
@llcruz1 

- [Matriz Perfil x Funcionalidade](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Matriz-Perfil-x-Funcionalidade)

Defini os perfis de acesso ADM e Visitante e adicionei as seguintes telas no protótipo:

- [Login](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Login)
- [Partidas Visitante](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Partidas#perfil-de-acesso-visitante)
- [Ranking Visitante](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Ranking#perfil-de-acesso-visitante)
- [Perfil](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Perfil)

Adicionei novas funcionalidades relacionadas ao cadastro de adms nas páginas:

- [Cadastros](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Cadastros)
- [ADMs](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/ADMs)
- [Novo ADM](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Novo-ADM)

Tempo estimado na tarefa: 3hrs
