### ISSUE TITLE
PSW - Programação back-end (Jogador)

### ISSUE THREAD

**Issue by Lucaslsps** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#43]

**Comment by llcruz1** [comment]
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/blob/main/src/back-end/models/jogadores.js

https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/blob/main/src/back-end/routes/jogadores.js

Tempo estimado: 1 hora
