### ISSUE TITLE
PSW - Programação back-end (Time)

### ISSUE THREAD

**Issue by Lucaslsps** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#44]

**Comment by llcruz1** [comment]
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/blob/main/src/back-end/routes/times.js
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/blob/main/src/back-end/models/times.js

Tempo estimado: 1 hora
