### ISSUE TITLE
PSW - Configuração do ambiente

### ISSUE THREAD

**Issue by misterx901** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#5]
Tarefa: Configuração do ambiente (rodar até a seção 4.7 do config.md)

Artefato: [Config.md](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/tree/main/src/front-end)
Horas Gastas: 1 hora.

Data Máxima de entrega: 12/11/2020 Horário: 12:00

**Comment by llcruz1** [comment]
@llcruz1 
[https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/tree/main/src/front-end](url)
Tempo estimado na tarefa: 1hr
