### ISSUE TITLE
Arquitetura - Ajustes sprint passada

### ISSUE THREAD

**Issue by Lucaslsps** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#54]

**Comment by bruna-capistrano** [comment]
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Arquitetura-As-Is
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/wiki/Arquitetura-To-Be
