### ISSUE TITLE
PSW - Criar HTML Das Telas

### ISSUE THREAD

**Issue by misterx901** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#6]
Tarefa: (opcional) começar a produzir o HTML das telas.

Data Máxima de entrega: 12/11/2020 Horário: 12:00

**Comment by llcruz1** [comment]
Jsx nos forms e tabelas:
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/tree/main/src/front-end/src/components

Drawer e appbar:
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5/tree/main/src/front-end/src/components/layout

Tempo estimado: 2hrs
