### ISSUE TITLE
Testes - Casos de testes de aceitação

### ISSUE THREAD

**Issue by misterx901** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#8]
Tarefa: Passar de especificação dos testes de aceitação para os casos de teste de aceitação, para isto precisarão incluir os dados que serão usados em cada caso de teste. A equipe de PSW definirá os domínios dos campos.

Data Máxima de entrega: 12/11/2020 Horário: 12:00

**Comment by Lucaslsps** [comment]
Gastas 6h
