### ISSUE TITLE
Testes - Estudar Gherkin

### ISSUE THREAD

**Issue by misterx901** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-5#9]
Tarefa: Estudar a linguagem Gherkin e passar os casos de teste para esta linguagem. Não precisa ter a implementação em javascript ainda, mas sim os arquivos .feature.

Data Máxima de entrega: 12/11/2020 Horário: 12:00

**Comment by Lucaslsps** [comment]
Gastas 5h
